### ISSUE TITLE
Document Special Cases for Variable Behavior in SDK

### ISSUE THREAD

**Issue by andrewdmaclean** [DevCycleHQ/devcycle-docs#391]
## Description
Currently, the documentation for the SDK's variables does not cover some specific scenarios that could be useful for users to understand. These include:

- How a variable will default if the server sends a data type different than what the code expects.
- The behavior of variables when a user does not qualify for targeting.
- Possibility to set up a fallback variation manually.

The aim is to decide whether these special cases deserve their own section in the documentation, can be incorporated into existing sections, or are already covered somewhere.

## Steps to Reproduce
1. Open the SDK Documentation on variables.
2. Look for information about the special cases listed above.

## Expected Behavior
The documentation should provide clear information on these special cases for variables to guide users through best practices and how to handle these cases.

## Actual Behavior
Currently, the documentation does not explicitly cover these scenarios.

## Additional Context
The absence of these explanations could lead to misconceptions or misunderstandings about how variables behave under specific conditions.

**Comment by cdruxerman** [comment]
Moved to internal tracker
