### ISSUE TITLE
Add Documentation for Migrating from Taplytics to DevCycle

### ISSUE THREAD

**Issue by andrewdmaclean** [DevCycleHQ/devcycle-docs#392]
## Description
As we are seeing an increasing number of users migrating from Taplytics to DevCycle, it would be beneficial to have a dedicated migration guide. This guide should aim to provide clear, step-by-step instructions on how to move projects, features, and other configurations from Taplytics to DevCycle.

## Suggested Solution
Create a new section in the documentation dedicated to migration. This section should cover:

- Preliminary steps and considerations before migration.
- A checklist of items to be migrated.
- Step-by-step guide for each type of migration (Feature Flags, Experiments, User Segmentation, etc.)
- Troubleshooting common issues.
- Best practices for testing the migration.

## Alternatives Considered
Another option could be to add migration tips and notes within the existing sections of the documentation, but this could scatter the information and make it hard for users specifically looking to migrate from Taplytics to find all the relevant details.

**Comment by andrewdmaclean** [comment]
Adding additional context here based on our knowledge of the process to date:
> 
> Install the relevant DevCycle SDK and choose a date. From that point on you'll create all new feature flags in DevCycle.
> 
> If there are still a handful of long-lived flags within Taplytics that you want to migrate over to DevCycle, you can wrap these flags in an IF statement and this would be the check:
> 
> - If the request to get the flag value from DevCycle returns with no data (i.e. the flag was deleted, doesn't exist or hasn't been added to DevCycle yet):
>     - Make a second request to Taplytics for the same flag value
> - If the request to get the flag value from DevCycle returns with a value:
>     - Use this value. There is no need to make a second call to Taplytics.
> 
> ```
> function getVariableValue(key: string, defaultValue: VariableValue) {
> 
>   // check DevCycle first
>   const dvcVariable = devcycleClient.variable(key, defaultValue)
> 
> 	// if we get a value back from DevCycle, return that value and end the function
>   if (!dvcVariable.isDefaulted) {
>      return dvcVariable
>   }
> 
>   // if dvcVariable is defaulted, there is a need to do a double-check in TL
>   const tlVariable = TL.variable(key, defaultValue)
> 
> 	// if we get a value back from Taplytics, return that value and end the function. Otherwise use the default value from DevCycle. 
>   if (!tlVariable.isDefaulted) {
>      return tlVariable
>   } else {
>      return dvcVariable
>   }
> }
> ```
> 
> We recommend double-checking that the value returned from the function above is aligned with what was expected by checking Taplytics and DevCycle.“

**Comment by cdruxerman** [comment]
Moved to internal tracker
